# Generated by Django 5.1.15 on 2026-07-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usertoken_alter_user_managers_user_avatar_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_reply_to',
            field=models.EmailField(blank=True, help_text='Shared inbox for replies. Overrides per-SMTP Reply-To when set.', max_length=254),
        ),
    ]
