# Generated by Django 5.1.15 on 2026-07-13 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('subscribers', '0003_rename_subscribers_list_id_added_idx_subscribers_list_id_1e2d50_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('open', 'Open'), ('click', 'Click'), ('bounce', 'Bounce'), ('complaint', 'Complaint'), ('unsubscribe', 'Unsubscribe')], db_index=True, max_length=20)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='campaigns.campaign')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'event_type'], name='tracking_tr_owner_i_b51ac8_idx'), models.Index(fields=['campaign', 'event_type'], name='tracking_tr_campaig_8449e6_idx')],
            },
        ),
    ]
