# Generated by Django 5.1.15 on 2026-07-15 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePurpose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_purposes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MessageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(choices=[('v1', 'V1'), ('v2', 'V2'), ('v3', 'V3')], max_length=2)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('html_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='email_templates.messagepurpose')),
            ],
            options={
                'ordering': ['purpose__name', 'version'],
            },
        ),
        migrations.AddConstraint(
            model_name='messagepurpose',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_message_purpose_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='messageversion',
            constraint=models.UniqueConstraint(fields=('purpose', 'version'), name='unique_version_per_message_purpose'),
        ),
    ]
