# Generated by Django 5.1.15 on 2026-07-13 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('smtp_servers', '0001_initial'),
        ('subscribers', '0003_rename_subscribers_list_id_added_idx_subscribers_list_id_1e2d50_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='campaigns.campaign')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_queue_items', to=settings.AUTH_USER_MODEL)),
                ('smtp_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_items', to='smtp_servers.smtpserver')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='sending_ema_campaig_06087a_idx'), models.Index(fields=['owner', 'status'], name='sending_ema_owner_i_a2e74b_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'subscriber'), name='unique_queue_item_per_campaign_subscriber')],
            },
        ),
    ]
