# Generated by Django 5.1.15 on 2026-07-15 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('sending', '0001_initial'),
        ('smtp_servers', '0003_add_imap_sent_copy'),
        ('subscribers', '0004_subscriber_company_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailqueueitem',
            index=models.Index(fields=['owner', 'sent_at'], name='sending_ema_owner_i_37bf9d_idx'),
        ),
    ]
