# Generated by Django 5.1.15 on 2026-07-13 11:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained')], db_index=True, default='subscribed', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('api', 'API')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='subscribers.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='lists',
            field=models.ManyToManyField(blank=True, related_name='subscribers', through='subscribers.ListMembership', to='subscribers.subscriberlist'),
        ),
        migrations.AddField(
            model_name='listmembership',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='subscribers.subscriberlist'),
        ),
        migrations.AddIndex(
            model_name='subscriberlist',
            index=models.Index(fields=['owner', 'is_active'], name='subscribers_owner_i_0d9fa3_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriberlist',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_subscriber_list_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['owner', 'status'], name='subscribers_owner_i_137df3_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['owner', 'email'], name='subscribers_owner_i_7110af_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(fields=('owner', 'email'), name='unique_subscriber_email_per_owner'),
        ),
        migrations.AddIndex(
            model_name='listmembership',
            index=models.Index(fields=['list', 'subscribed_at'], name='subscribers_list_id_bb70db_idx'),
        ),
        migrations.AddConstraint(
            model_name='listmembership',
            constraint=models.UniqueConstraint(fields=('list', 'subscriber'), name='unique_list_subscriber_membership'),
        ),
    ]
