# Generated by Django 5.1.15 on 2026-07-13 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscriber_phone_subscribed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listmembership',
            new_name='subscribers_list_id_1e2d50_idx',
            old_name='subscribers_list_id_added_idx',
        ),
        migrations.AddIndex(
            model_name='subscriberlist',
            index=models.Index(fields=['owner', 'name'], name='subscribers_owner_i_0425b7_idx'),
        ),
    ]
