# Generated by Django 5.1.15 on 2026-07-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_rename_subscribers_list_id_added_idx_subscribers_list_id_1e2d50_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='industrial_company',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
