# Generated by Django 5.1.15 on 2026-07-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_subscriber_company_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberlist',
            name='source_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
