# Generated by Django 5.1.15 on 2026-07-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0005_list_source_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
