# Generated by Django 5.1.15 on 2026-07-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0006_subscriber_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberlist',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
