[program:email_platform_gunicorn]
command=/var/www/email_platform/.venv/bin/gunicorn config.wsgi:application -c /var/www/email_platform/deployment/gunicorn/gunicorn.conf.py
directory=/var/www/email_platform/backend
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/email_platform_gunicorn.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
environment=DJANGO_SETTINGS_MODULE="config.settings.production"
stopwaitsecs=30
killasgroup=true
stopasgroup=true

[program:email_platform_celery_worker]
command=/var/www/email_platform/.venv/bin/celery -A config worker --loglevel=INFO --concurrency=4
directory=/var/www/email_platform/backend
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/email_platform_celery_worker.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
environment=DJANGO_SETTINGS_MODULE="config.settings.production"
stopwaitsecs=600
killasgroup=true
stopasgroup=true

[program:email_platform_celery_beat]
command=/var/www/email_platform/.venv/bin/celery -A config beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
directory=/var/www/email_platform/backend
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/email_platform_celery_beat.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
environment=DJANGO_SETTINGS_MODULE="config.settings.production"
stopwaitsecs=30
killasgroup=true
stopasgroup=true

[group:email_platform]
programs=email_platform_gunicorn,email_platform_celery_worker,email_platform_celery_beat
priority=999
