# Generated by Django 5.1.15 on 2026-07-22 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smtp_servers', '0005_add_unibox_and_warmup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mailbox_email', models.EmailField(blank=True, max_length=254)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=512)),
                ('imap_uid', models.CharField(blank=True, max_length=64)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('to_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('snippet', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_messages', to=settings.AUTH_USER_MODEL)),
                ('smtp_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_messages', to='smtp_servers.smtpserver')),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'is_read'], name='inbox_inbox_owner_i_979276_idx'), models.Index(fields=['owner', '-received_at'], name='inbox_inbox_owner_i_5bf862_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'smtp_server', 'imap_uid'), name='unique_inbox_uid_per_mailbox')],
            },
        ),
    ]
