# Generated by Django 5.1.15 on 2026-07-22 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_add_unibox_and_warmup'),
        ('smtp_servers', '0005_add_unibox_and_warmup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxMailbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('username', models.CharField(max_length=255)),
                ('password_encrypted', models.TextField()),
                ('verify_ssl', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='inboxmessage',
            name='unique_inbox_uid_per_mailbox',
        ),
        migrations.AddField(
            model_name='inboxmailbox',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_mailboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboxmessage',
            name='mailbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inbox.inboxmailbox'),
        ),
        migrations.AddConstraint(
            model_name='inboxmessage',
            constraint=models.UniqueConstraint(fields=('owner', 'mailbox', 'imap_uid'), name='unique_inbox_uid_per_unibox_mailbox'),
        ),
        migrations.AddConstraint(
            model_name='inboxmailbox',
            constraint=models.UniqueConstraint(fields=('owner', 'email'), name='unique_inbox_mailbox_email_per_owner'),
        ),
    ]
