# Generated by Django 5.1.15 on 2026-07-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp_servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpserver',
            name='verify_ssl',
            field=models.BooleanField(default=False, help_text='Verify the SMTP server SSL certificate. Disable for shared hosting.'),
        ),
    ]
