# Generated by Django 5.1.15 on 2026-07-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp_servers', '0003_add_imap_sent_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpserver',
            name='reply_to_email',
            field=models.EmailField(blank=True, help_text='Optional Reply-To for this sender. If blank, uses account default_reply_to, else the From address.', max_length=254),
        ),
    ]
