# Generated by Django 5.1.15 on 2026-07-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp_servers', '0004_add_default_reply_to_and_smtp_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpserver',
            name='warmup_current_daily',
            field=models.PositiveIntegerField(default=0, help_text='Current effective daily cap while warming up. 0 = use start.'),
        ),
        migrations.AddField(
            model_name='smtpserver',
            name='warmup_enabled',
            field=models.BooleanField(default=False, help_text='When on, daily sends ramp from start to target instead of full daily_limit.'),
        ),
        migrations.AddField(
            model_name='smtpserver',
            name='warmup_increase_daily',
            field=models.PositiveIntegerField(default=5, help_text='How many emails to add to the warmup cap each day.'),
        ),
        migrations.AddField(
            model_name='smtpserver',
            name='warmup_start_daily',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='smtpserver',
            name='warmup_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpserver',
            name='warmup_target_daily',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
